# Generated by Django 4.2.5 on 2023-09-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconImage', models.ImageField(upload_to='static/images')),
                ('sTitle', models.CharField(max_length=255)),
                ('sDesc', models.TextField()),
            ],
        ),
    ]
