# Generated by Django 4.2.5 on 2023-09-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconImage', models.ImageField(upload_to='adv/static/images')),
                ('sTitle', models.CharField(max_length=255)),
                ('sDesc', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
