# Generated by Django 4.2.5 on 2023-09-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0002_services_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gPhoto', models.ImageField(upload_to='adv/static/images')),
                ('gName', models.CharField(max_length=255)),
                ('gPos', models.TextField()),
            ],
        ),
    ]
