# Generated by Django 4.2.5 on 2023-09-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0003_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=255)),
                ('cEmail', models.EmailField(max_length=254)),
                ('cPhone', models.PositiveBigIntegerField()),
                ('cMsg', models.TextField()),
            ],
        ),
    ]
