# Generated by Django 4.2.5 on 2023-10-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0005_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eId', models.CharField(max_length=255)),
                ('eName', models.CharField(max_length=255)),
                ('eEmail', models.EmailField(max_length=254)),
                ('eContact', models.CharField(max_length=255)),
            ],
        ),
    ]
